# PARENT_ITEM_ID에 없는 ID는 업그레이드 불가 ID
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO II
WHERE NOT EXISTS (
        SELECT IT.PARENT_ITEM_ID
        FROM ITEM_TREE IT
        WHERE II.ITEM_ID = IT.PARENT_ITEM_ID
    )
ORDER BY ITEM_ID DESC;