SELECT C.CAR_ID, C.CAR_TYPE, 
    ROUND(C.DAILY_FEE * (100-P.DISCOUNT_RATE)/100 * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H 
ON C.CAR_ID = H.CAR_ID
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P 
ON C.CAR_TYPE = P.CAR_TYPE  AND P.DURATION_TYPE = '30일 이상'
WHERE C.CAR_TYPE IN ('세단', 'SUV')
AND C.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE >= '2022-10-31' AND START_DATE <= '2022-11-30'
    )
GROUP BY C.CAR_ID, C.CAR_TYPE
HAVING 500000 <= FEE AND FEE < 2000000 
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;