SELECT CAR_ID,
    CASE
        WHEN EXISTS (
            SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE CAR_ID = C.CAR_ID
            AND START_DATE <= '2022-10-16' 
            AND '2022-10-16' <= END_DATE
        ) THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;