SELECT FH.FLAVOR
FROM FIRST_HALF AS FH
INNER JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) J ON FH.FLAVOR = J.FLAVOR
ORDER BY FH.TOTAL_ORDER + J.JULY_TOTAL_ORDER DESC
LIMIT 3;
