SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM FISH_INFO AS FI
INNER JOIN FISH_NAME_INFO AS FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE FI.ID = (
    SELECT ID
    FROM FISH_INFO
    WHERE FISH_TYPE = FI.FISH_TYPE
    ORDER BY LENGTH DESC
    LIMIT 1
)